 // generated by GenNgService.go
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Kamar : Ajout d'un moyen pour communiquer entre les composants qui partagent de l'information
 * afin qu'ils soient notifiés d'un changement.
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { AAPI } from './a-api';
import { ADB } from './a-db';



@Injectable({
  providedIn: 'root'
})
export class AService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  AServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private asUrl = 'http://localhost:8080/as';

  constructor(
    private http: HttpClient
  ) { }

  /** GET as from the server */
  getAs(): Observable<ADB[]> {
    return this.http.get<ADB[]>(this.asUrl)
      .pipe(
        tap(_ => this.log('fetched as')),
        catchError(this.handleError<ADB[]>('getAs', []))
      );
  }

  /** GET a by id. Will 404 if id not found */
  getA(id: number): Observable<ADB> {
    const url = `${this.asUrl}/${id}`;
    return this.http.get<ADB>(url).pipe(
      tap(_ => this.log(`fetched a id=${id}`)),
      catchError(this.handleError<ADB>(`getA id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new a to the server */
  postA(aAPI: AAPI): Observable<ADB> {
    return this.http.post<ADB>(this.asUrl, aAPI, this.httpOptions).pipe(
      tap((newA: ADB) => this.log(`added a w/ id=${newA.ID}`)),
      catchError(this.handleError<ADB>('addA'))
    );
  }

  /** DELETE: delete the adb from the server */
  deleteA(adb: ADB | number): Observable<ADB> {
    const id = typeof adb === 'number' ? adb : adb.ID;
    const url = `${this.asUrl}/${id}`;

    return this.http.delete<ADB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted adb id=${id}`)),
      catchError(this.handleError<ADB>('deleteA'))
    );
  }

  /** PUT: update the adb on the server */
  updateA(adb: ADB): Observable<ADB> {
    const id = typeof adb === 'number' ? adb : adb.ID;
    const url = `${this.asUrl}/${id}`;

    return this.http.put(url, adb, this.httpOptions).pipe(
      tap(_ => this.log(`updated adb id=${adb.ID}`)),
      catchError(this.handleError<ADB>('updateA'))
    );
  }



  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
