// generated by "genNgIndex.go"
/*
* Public API Surface of A
*/

export * from './lib/a.module'

export * from './lib/splitter/splitter.component'
export * from './lib/sidebar/sidebar.component'


export * from './lib/aclass-detail/aclass-detail.component'
export * from './lib/aclass-adder/aclass-adder.component'
export * from './lib/aclass-presentation/aclass-presentation.component'
export * from './lib/aclasss-table/aclasss-table.component'
export * from './lib/aclass-db'
export * from './lib/aclass-api'
export * from './lib/aclass.service'


