// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { ADB } from '../a-db'
import { AService } from '../a.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-a-detail',
  templateUrl: './a-detail.component.html',
  styleUrls: ['./a-detail.component.css']
})
export class ADetailComponent implements OnInit {

	// the ADB of interest
	a: ADB;

	constructor(
		private aService: AService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getA();

  }

  getA(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.aService.getA(id)
		.subscribe( 
			a => 
			{ 
					this.a = a

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.aService.updateA( this.a )
    .subscribe(a => {
		this.aService.AServiceChanged.next("update")

    	console.log("a saved")
    });
  }
}
