// generated by "genNgIndex.go"
/*
* Public API Surface of B
*/

export * from './lib/b.module'

export * from './lib/splitter/splitter.component'
export * from './lib/sidebar/sidebar.component'


export * from './lib/bclass-detail/bclass-detail.component'
export * from './lib/bclass-adder/bclass-adder.component'
export * from './lib/bclass-presentation/bclass-presentation.component'
export * from './lib/bclasss-table/bclasss-table.component'
export * from './lib/bclass-db'
export * from './lib/bclass-api'
export * from './lib/bclass.service'


