// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { BclassDB } from '../bclass-db'
import { BclassService } from '../bclass.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-bclass-detail',
  templateUrl: './bclass-detail.component.html',
  styleUrls: ['./bclass-detail.component.css']
})
export class BclassDetailComponent implements OnInit {

	// the BclassDB of interest
	bclass: BclassDB;

	constructor(
		private bclassService: BclassService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getBclass();

  }

  getBclass(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.bclassService.getBclass(id)
		.subscribe( 
			bclass => 
			{ 
					this.bclass = bclass

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.bclassService.updateBclass( this.bclass )
    .subscribe(bclass => {
		this.bclassService.BclassServiceChanged.next("update")

    	console.log("bclass saved")
    });
  }
}
